config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
    
  get 'email-items', to: 'portfolios#emails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  
  resources :blogs do
  	member do	
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title

	has_many :blogs

	def self.with_blogs
		includes(:blogs).where.not(blogs: { id: nil})
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :set_sidebar_topics
	layout 'blog'
  access all: [:index, :show], site_admin: :all

  def index
  	@topics = Topic.all
  end

  def show
  	if logged_in?(:site_admin)
      @blogs = @topic.blogs.recent.page(params[:page]).per(5)
    else
      @blogs = @topic.blogs.published.recent.page(params[:page]).per(5)
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_path, notice: 'Topic was successfully deleted.' }
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title)
  end

  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <% topic.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Topic Title' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to "Cancel", topics_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div class='card col-md-5'>
	<%= link_to topic.title, topic_path(topic) %>
	<% if logged_in?(:site_admin) %>
		<div class="mt-2">
			<%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-sm btn-warning' %>
			<%= link_to 'Delete', topic_path(topic), method: :delete, data: { confirm: 'Are you sure? This will not delete associated blogs.' }, class: 'btn btn-sm btn-danger' %>
		</div>
	<% end %>
</div>

app/views/topics/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Edit Topic</h1>

  <%= render 'form', topic: @topic %>
</div>

app/views/topics/index.html.erb
<div class="col-sm-8 blog-main">

	<div class="d-flex justify-content-between align-items-center mb-3">
		<h1>Topics</h1>
		<% if logged_in?(:site_admin) %>
			<%= link_to "New Topic", new_topic_path, class: 'btn btn-primary' %>
		<% end %>
	</div>

  <div class='topic-index row'>
    <%= render @topics %>
  </div>

</div>

app/views/topics/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>Create a New Topic</h1>

  <%= render 'form', topic: @topic %>
</div>

app/views/topics/show.html.erb
<div class="col-sm-8 blog-main">

	<div class="d-flex justify-content-between align-items-center mb-3">
		<h1 style="font-size: 2rem; color: #888;"><%= @topic.title %></h1>
		<% if logged_in?(:site_admin) %>
			<div>
				<%= link_to 'Edit Topic', edit_topic_path(@topic), class: 'btn btn-warning' %>
				<%= link_to 'Delete Topic', topic_path(@topic), method: :delete, data: { confirm: 'Are you sure? This will not delete associated blogs.' }, class: 'btn btn-danger' %>
			</div>
		<% end %>
	</div>

	<%= paginate @blogs %>

  <%= render @blogs %>

  <%= paginate @blogs %>
</div>