config/routes.rb
Rails.application.routes.draw do
  resources :topics

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
    
  get 'email-items', to: 'portfolios#emails'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  
  resources :blogs do
  	member do	
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= @copyright %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
  	<a a href="/"><h3 class="masthead-brand">Linards Berzins</h3></a>
      <nav class="nav nav-masthead app-nav">
        <%= nav_helper 'nav-link', 'span' %>
        <%= login_helper 'nav-link' %>
      </nav>
   </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="text-muted" style="padding-top: 3rem; padding-bottom: 3rem;">
	<div class="container">
	  <p class="float-right">
	  <%= link_to "View all blogs", blogs_path, style: "color: #358399;" %> /
	    <a href="#" style="color: #358399;">Back to top</a>
	  </p>
	  <style>
	    footer a:hover {
	      color: #993550 !important;
	      text-decoration: none;
	    }

	    @media (max-width: 575px) {
	      footer .float-right {
	        float: none !important;
	        text-align: center;
	        margin-bottom: 0.5rem;
	      }

	      footer .container {
	        text-align: center;
	      }
	    }
	  </style>
	  <%= @copyright %>
	</div>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
	<div class="container">
	  <h1 class="blog-title">Blog</h1>
	  <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin)%>
	  <span class="topics-link">
	  	<%= link_to 'Topics', topics_path %>
	  </span>
	</div>
</div>

app/views/shared/_blog_nav.html.erb
<header>
	<div class="collapse" id="navbarHeader" style="background-color: #FFFFFF; border-bottom: 1px solid #dee2e6;">
	  <div class="container">
	    <div class="row">
	      <div class="col-sm-11 py-4">
	        <p class="text-justify" style="color: #343a40;">Blog posts about #AI #promptengineering and #VibeCoding</p>
	      </div>
	      <div class="col-sm-1 py-4 text-right">
	        <ul class="list-unstyled">
	          <%= nav_helper 'text-dark', 'li' %>
					<li><%= login_helper 'text-dark' %></li>
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="navbar" style="background-color: #FFFFFF;">
	  <div class="container d-flex justify-content-between">
	    <a href="/" class="navbar-brand" style="color: #868e96;">Linards Berzins</a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation" style="border-color: #868e96;">
	      <span class="navbar-toggler-icon" style="background-image: url(&quot;data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'%3e%3cpath stroke='%23868e96' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e&quot;);"></span>
	    </button>
	  </div>
	</div>
</header>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module social_text">
    <ol class="list-unstyled social_links">
      <li style="padding: 0 10px;"><a href="https://www.linkedin.com/in/linardsberzins/"><%= fa_icon "linkedin" %></a></li>
      <li style="padding: 0 10px;"><a href="https://github.com/linardsb"><%= fa_icon "github" %></a></li>
    </ol>
  </div>
 
  <% if @side_bar_topics %>
      <div class="sidebar-module social_text">
        <h4>topics</h4>
        <% @side_bar_topics.each do |topic| %>
          <p><%= link_to topic.title, topic_path(topic) %></p>
        <% end %>
      </div>
    <% end %>


</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
	<div class="container">
	  <p class="float-right">
	  <%= link_to "View all portfolios", portfolios_path %> /
	    <a href="#">Back to top</a>
	  </p>
	  <%= @copyright %>  
	</div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<header>
	<div class="collapse" id="navbarHeader" style="background-color: #FFFFFF; border-bottom: 1px solid #dee2e6;">
	  <div class="container">
	    <div class="row">
	      <div class="col-sm-11 py-4">
	        <p class="text-justify" style="color: #343a40;">Email and other portfolio items</p>
	      </div>
	      <div class="col-sm-1 py-4 text-right">
	        <ul class="list-unstyled">
	          <%= nav_helper 'text-dark', 'li' %>
					<li style="margin-bottom: 0.6rem;"><%= login_helper 'text-dark' %></li>
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="navbar" style="background-color: #FFFFFF;">
	  <div class="container d-flex justify-content-between">
	    <a href="/" class="navbar-brand" style="color: #868e96;">Linards Berzins</a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation" style="border-color: #868e96;">
	      <span class="navbar-toggler-icon" style="background-image: url(&quot;data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'%3e%3cpath stroke='%23868e96' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e&quot;);"></span>
	    </button>
	  </div>
	</div>
</header>